// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrTdwHR8Mxez42vw2NEIsiew-sF0u3fg',
    appId: '1:6924894690:web:545a3f221023b07c7e79bb',
    messagingSenderId: '6924894690',
    projectId: 'flash-chat-kurs20-911e7',
    authDomain: 'flash-chat-kurs20-911e7.firebaseapp.com',
    storageBucket: 'flash-chat-kurs20-911e7.appspot.com',
    measurementId: 'G-71H00YHLS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBROXLwqNF70CSG4Nz1s98MmK9Ozq_2I48',
    appId: '1:6924894690:android:abd39407acaf32817e79bb',
    messagingSenderId: '6924894690',
    projectId: 'flash-chat-kurs20-911e7',
    storageBucket: 'flash-chat-kurs20-911e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-ZAT-Tk_2xylDPtMt1uaRbkF97VvEVE',
    appId: '1:6924894690:ios:912e1bcde3e0485d7e79bb',
    messagingSenderId: '6924894690',
    projectId: 'flash-chat-kurs20-911e7',
    storageBucket: 'flash-chat-kurs20-911e7.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-ZAT-Tk_2xylDPtMt1uaRbkF97VvEVE',
    appId: '1:6924894690:ios:912e1bcde3e0485d7e79bb',
    messagingSenderId: '6924894690',
    projectId: 'flash-chat-kurs20-911e7',
    storageBucket: 'flash-chat-kurs20-911e7.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmrTdwHR8Mxez42vw2NEIsiew-sF0u3fg',
    appId: '1:6924894690:web:87cf8a42dd5c3be27e79bb',
    messagingSenderId: '6924894690',
    projectId: 'flash-chat-kurs20-911e7',
    authDomain: 'flash-chat-kurs20-911e7.firebaseapp.com',
    storageBucket: 'flash-chat-kurs20-911e7.appspot.com',
    measurementId: 'G-B555P2BJN6',
  );
}
